
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a 'master' si ese es tu branch principal
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

# Permisos necesarios para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita que múltiples despliegues se ejecuten simultáneamente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js (si usas Node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Usa 'yarn' si prefieres yarn

      - name: Instalar dependencias
        run: npm ci

      - name: Build del proyecto
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

  # Job de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4